/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AAvatar: (typeof import('ant-design-vue/es'))['Avatar']
    AAvatarGroup: (typeof import('ant-design-vue/es'))['AvatarGroup']
    ABackTop: (typeof import('ant-design-vue/es'))['BackTop']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: (typeof import('ant-design-vue/es'))['Card']
    ACardMeta: (typeof import('ant-design-vue/es'))['CardMeta']
    ACheckbox: (typeof import('ant-design-vue/es'))['Checkbox']
    ACheckboxGroup: (typeof import('ant-design-vue/es'))['CheckboxGroup']
    ACollapse: (typeof import('ant-design-vue/es'))['Collapse']
    ACollapsePanel: (typeof import('ant-design-vue/es'))['CollapsePanel']
    ADivider: (typeof import('ant-design-vue/es'))['Divider']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AEmpty: typeof import('ant-design-vue/es')['Empty']
    AFloatButton: typeof import('ant-design-vue/es')['FloatButton']
    AForm: (typeof import('ant-design-vue/es'))['Form']
    AFormItem: (typeof import('ant-design-vue/es'))['FormItem']
    AInput: (typeof import('ant-design-vue/es'))['Input']
    AInputSearch: (typeof import('ant-design-vue/es'))['InputSearch']
    ALayoutHeader: (typeof import('ant-design-vue/es'))['LayoutHeader']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AModal: (typeof import('ant-design-vue/es'))['Modal']
    APageHeader: typeof import('ant-design-vue/es')['PageHeader']
    APopconfirm: (typeof import('ant-design-vue/es'))['Popconfirm']
    AProgress: (typeof import('ant-design-vue/es'))['Progress']
    ARadio: (typeof import('ant-design-vue/es'))['Radio']
    ARadioGroup: (typeof import('ant-design-vue/es'))['RadioGroup']
    ASelect: (typeof import('ant-design-vue/es'))['Select']
    ASelectOption: (typeof import('ant-design-vue/es'))['SelectOption']
    ASpace: (typeof import('ant-design-vue/es'))['Space']
    ASwitch: (typeof import('ant-design-vue/es'))['Switch']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    ATag: (typeof import('ant-design-vue/es'))['Tag']
    ATextarea: (typeof import('ant-design-vue/es'))['Textarea']
    ATooltip: (typeof import('ant-design-vue/es'))['Tooltip']
    ATree: (typeof import('ant-design-vue/es'))['Tree']
    ATreeSelect: (typeof import('ant-design-vue/es'))['TreeSelect']
    EmptyStatus: typeof import('./src/components/EmptyStatus/index.vue')['default']
    PreviewEditor: (typeof import('./src/components/PreviewEditor/index.vue'))['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/SvgIcon/index.vue')['default']
  }
}
